### PR TITLE
Add `dotenv_iter`, which returns iterator over `.env.` entries

### LINKED ISSUE #74: Consider making .env variable iterator or vec available
I would like to be able to load variables from a `.env` file, but would like to avoid putting them into the current process's environment, instead putting them into a child process's environment using `process::Command::env`.

Would it be possible to allow loading variables from a `.env` file, but only providing an iterator or vec of them, instead of loading them into the current process's environment?

### PR DESCRIPTION
**Pull request by casey**
Heyo!

I wound up doing a lot of refactoring, which I hope you think is okay. I did the following:

- Moved error handling and parsing into separate modules, to aid readability. This leaves only public items in `lib.rs`.
- Added a `iter::Iter`, which iterates over `.env` values, and added a method on it to load them into the environment
- Moved `try_dir_with_parents` into `find::find`, which looks for a dotenv file without loading it
- Ran rustfmt on the code, which seems to have only produced a few minor diffs

I only added `dotenv::dotenv_iter`, which is like `dotenv::dotenv` but returns an iterator, since that was the one I needed for my own uses. Should I also add `_iter` methods for the other ways of loading a dotenv file?

Of course, formatting and organization are pretty subjective, so I welcome your feedback and suggestions.

Thanks!

Fixes #74

### CODE REVIEW

**Comment by casey** [comment]
A couple of updates:

- It looks like `--doc` takes precedence over `--lib`, so `--lib` tests weren't running on travis
- I switched the parser tests to use `Iter`, so that there is some test coverage

**Comment by purpliminal** [comment]
Thanks for opening a PR! In particular, thank you for the refactor bits and noticing that the `--lib` tests weren't running on Travis -- oops!

I guess that, for the sake of consistency, there should be `_iter` methods for each loading mechanism? Other than that, it looks ready to merge to me 👍

**Comment by casey** [comment]
I refactored the tests so that they all run when invoking `cargo tests` from root. They're split into separate files, so that the environments don't conflict, and use `tempdir` to create and cd into a temporary directory with a `.env` file.

All the top-level functions now use the same code to find a `.env` file and load an iterator, reducing code duplication.

Also, I added examples for everything and comprehensive tests which test every top level function.

**Comment by purpliminal** [comment]
This is amazing. Thank you so much!

Merging 👍 💯 🐼

**Comment by casey** [comment]
Thank you! Very glad to help :)

**Comment by casey** [comment]
Would it be possible to push a new release to crates.io, so that I can update `just` to use the dotenv iterator?

**Comment by purpliminal** [comment]
Done! https://crates.io/crates/dotenv

**Comment by casey** [comment]
Sweet!

**Pull request merged**
