### PR TITLE
replace error-chain with failure

### PR DESCRIPTION
**Pull request by andy128k**

### CODE REVIEW

**Comment by daboross** [comment]
Any reasons as to why this would be preferred?

I can understand wanting to use failure in a new crate, but dotenv already has error handling. Switching this would be a breaking change, and IMO there needs to be a good reason to make changes requiring a semver break.

**Comment by purpliminal** [comment]
It seems like the whole Rust community is moving to Failure, so I wouldn't necessarily oppose this change. However, I don't really follow Rust that closely anymore, so a quick explanation would be appreciated.

**Comment by purpliminal** [comment]
Thanks, @andy128k! I’m okay with merging this if @daboross is.

**Comment by andy128k** [comment]
i've just removed extra error case, which was added by me mistakenly.

**Comment by daboross** [comment]
I'm all for it too then.

**Comment by daboross** [comment]
Actually, sorry for not seeing this:

It might be good to still depend on `failure` with `default-features = false` and with the `derive` feature, since failure also has a default feature depending on `backtrace`. I agree with failure it's nice we don't have to do anything to our code to change backtrack functionality- so we can just not depend on it, and someone can depend on failure themselves if they need that.

**Comment by andy128k** [comment]
@daboross I've just tried that. It looks problematic because `backtrace` dependency is under a feature-flag `std`. Switching it off leads to situation that wrapped errors (regex, std::io and std::env) do not implement Fail trait. Please have a look. It is really ugly now. :(

**Comment by daboross** [comment]
@andy128k Agh, yeah, I see what you mean. Might be better with `#[cfg_attr(feature = backtrace, cause)]` but that's still pretty bad. I was hoping we could do it without any `backtrace` feature in dotenv at all.

I know when error-chain was introduced, there were some users of dotenv who needed to build without the `backtrace` crate, putting us in the situation we're in now.

I've submitted an issue (https://github.com/withoutboats/failure/issues/127) for failure possibly implementing `std` errors without depending on `backtrace`. If that's possible to do, it seems like that would be a good thing to wait on before releasing this?

**Comment by sgrif** [comment]
Does dotenv even work without the standard library? I don't see why a backtrace feature is needed, we can just specify `features = ["std"]` on the failure crate.

**Comment by sgrif** [comment]
Also, it's probably worth a PR to the failure crate to make `#[cause]` not generate invalid code if the `backtrace` feature is disabled.

**Comment by daboross** [comment]
@sgrif the 'std' feature of failure depends on the backtrack feature.

**Comment by sgrif** [comment]
Right. That was my point. Given that situation (and that we require `std`), it seemed like a non-issue. After I wrote that I read https://github.com/withoutboats/failure/issues/127 and learned the intention to separate those features. If they are separated, it should be reasonable to expect that `#[cause]` doesn't generate invalid code based on features. For example, Diesel 1.1 provides `#[derive(SqlType)]` which implements `HasSqlType` for various backends based on information provided by certain attributes. Here's some example code:

```
#[derive(Debug, Clone, Copy, Default, QueryId, SqlType)]
#[postgres(oid = "23", array_oid = "1007")]
#[sqlite_type = "Integer"]
#[mysql_type = "Long"]
pub struct Integer;
```

This code compiles regardless of what features Diesel was compiled with. If Diesel was compiled without PG support, the `postgres` attribute does nothing.

**Comment by sgrif** [comment]
With all of that said, I'm also still not sure this is a real issue. Is there any real reason to *avoid* the backtrace dependency?

**Comment by daboross** [comment]
@sgrif ah, sorry, maybe I'm misunderstanding the nature of the `std` problem with `failure`.

It was my understanding that `#[cause]` still generates the same valid code when compiled without 'backtrace' or without 'std', but that it always requires `failure::Fail` to be implemented for the inner error type, and that without the 'std' feature, neither `std::io::Error` nor `regex::Error` implement `failure::Fail`.

As for why we'd want to avoid the backtrace dependency, I'm pretty much just mirroring concerns brought up by @golddranks in https://github.com/purpliminal/rust-dotenv/issues/65.

If failure is going to release a breaking implementing std/backtrace feature independence anyways, it seems reasonable to me to wait for that. However, that's just my conservative reasoning wanting to not release two new breaking changes to dotenv when they could just be one.

**Comment by golddranks** [comment]
Note that the issue with backtrace was because of slowness on MacOS. At least part of that was due to resolving symbols even they were not needed. I now think that religiously avoiding backtraces might not be needed, if the implementation doesn't use the slow path by default. I.e. maybe it should be a concern of the Failure crate and Error-chain, not the dependencies.

**Comment by daboross** [comment]
I think we're still waiting on a `0.2` release of failure- error_chain erroring is unfortunate, though.

Maybe we should just move back to manually creating errors for the time being? Fewer dependencies, even if it's a bit more code for formatting.

**Comment by Eijebong** [comment]
We're waiting for a `1.0` for failure which should've been out 3 months ago :/ I hope they get some time to do it soon-ish

**Comment by daboross** [comment]
Yeah.... In that case, merging now doesn't seem _too_ bad?

@purpliminal since it seems failure 0.2 (or now 1.0.0) isn't going to be coming any time soon, I'd be good with merging this PR now in its current state. We could merge this and then #100 to do both breaking changes, then update again after failure reaches 1.0?

**Comment by Eijebong** [comment]
@daboross The only problem with that is that you're going to depend on syn 0.11 :(

**Comment by daboross** [comment]
@Eijebong True, but it's a compile time dependency not a runtime one, so it shouldn't be _too_ bad. I mean it will mean our users need to download and compile it, but it won't mean any additional runtime cost or bloat when using dotenv.

**Comment by Eijebong** [comment]
Sure, just saying ^^ Most big projects already depend on failure anyway so they'll have it in their dependency tree already

**Comment by purpliminal** [comment]
@daboross Oops, I just went ahead and merged #100 before reading this, since there seemed to be consensus on it. That said, go for it!

**Pull request merged**
